### ISSUE TITLE
`style` usage

### ISSUE THREAD

**Issue by mpash** [wsoksoda/frontendpokedexnextJs#2]
We should remove all references to `style` inside any Chakra elements. They should have their CSS equivalent available as a property on the base component.

ie.
`style={{ minHeight: "100vh" }}` -> `minH="100vh"`

Also, please pay attention to when you have a single string value.
- [x] Remove all single-string props that look like this `fontSize={"3xl"}`, transform into `fontSize="3xl"`

**Comment by wsoksoda** [comment]
Style remains in desktopPokemonList and mobilePokemonList because it was the only way I could find to implement textDecoration
